openapi: 3.0.2
info:
  title: Defines a user update to be indexed
  version: 1.0.0
paths: {}

components:
  schemas:
    Stock:
      type: object
      properties:
        code:
          type: string
        adj_close:
          type: number
          format: float
        close:
          type: number
          format: float
        high:
          type: number
          format: float
        low:
          type: number
          format: float
        open:
          type: number
          format: float
        volume:
          type: integer

    StockUpdate:
      type: object
      properties:
        timestamp:
          type: string
        stocks:
          type: array
          items:
            $ref: '#/components/schemas/Stock'