openapi: 3.0.2
info:
  title: Defines a user update to be indexed
  version: 1.0.0
paths: {}

components:
  schemas:
    UserUpdate:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        id:
          type: string
        email:
          type: string
        phone:
          type: string
          nullable: true
        membership:
          type: object
          properties:
            status:
              type: string
            category:
              type: string
              nullable: true
        address:
          type: string
          nullable: true

    Stock:
      type: object
      properties:
        code:
          type: string
        adj_close:
          type: number
          format: float
        close:
          type: number
          format: float
        high:
          type: number
          format: float
        low:
          type: number
          format: float
        open:
          type: number
          format: float
        volume:
          type: integer

    StockUpdate:
      timestamp:
        type: string
        format: date-time
      stocks:
        type: array
        items:
          $ref: '#/components/schemas/Stock'